[25094] mobile number script
elexis/elexis-3-core pull request #507
Opened 2023-02-22 16:01 UTC by PatrickDenzler

2023-02-22 16:52 UTC, col-panic requested changes

2023-02-22 16:52 UTC, col-panic commented on bundles/ch.elexis.core.ui.dbcheck/src/ch/elexis/core/ui/dbcheck/contributions/SetMobileOfPatient.java
> +		patientQuery.and(ModelPackage.Literals.ICONTACT__PATIENT, COMPARATOR.EQUALS, true);
Warum auf Patienten limitieren?

2023-02-22 16:52 UTC, col-panic commented on bundles/ch.elexis.core.ui.dbcheck/src/ch/elexis/core/ui/dbcheck/contributions/SetMobileOfPatient.java
> +				if (patient.getPhone1() != null && !StringUtils.isBlank(patient.getPhone1())) {
wiederholung, StringUtils fasst das zusammen

2023-02-22 16:52 UTC, col-panic commented on bundles/ch.elexis.core.ui.dbcheck/src/ch/elexis/core/ui/dbcheck/contributions/SetMobileOfPatient.java
> +		return "Setzt Mobilnummer des Patienten, falls in anderem Feld vorhanden";
Wird nur gesetzt oder verschoben?

2023-02-22 16:52 UTC, col-panic commented on bundles/ch.elexis.core.ui.dbcheck/src/ch/elexis/core/ui/dbcheck/contributions/SetMobileOfPatient.java
> +
du kannst auch noch prüfen, ob PHONE1 oder PHONE2 ungleich null sind

2023-02-23 08:17 UTC, PatrickDenzler commented on bundles/ch.elexis.core.ui.dbcheck/src/ch/elexis/core/ui/dbcheck/contributions/SetMobileOfPatient.java
> +		return "Setzt Mobilnummer des Patienten, falls in anderem Feld vorhanden";
nur gesetzt

2023-02-23 13:32 UTC, PatrickDenzler commented on bundles/ch.elexis.core.ui.dbcheck/src/ch/elexis/core/ui/dbcheck/contributions/SetMobileOfPatient.java
> +
Es kann sein, dass PHONE1 null ist und PHONE2 die Mobilenummer hat

2023-02-24 14:15 UTC, merged