[25214] add pdf files to texttemplate
elexis/elexis-3-core pull request #519
Opened 2023-05-25 12:50 UTC by PatrickDenzler

2023-05-25 13:02 UTC, col-panic requested changes

2023-05-25 13:02 UTC, col-panic commented on bundles/ch.elexis.core.mail.ui/src/ch/elexis/core/mail/ui/preference/TextTemplates.java
> +						IBlobSecondary textTemplate = CoreModelServiceHolder.get().load(id, IBlobSecondary.class)
Ist das nicht `TEXTTEMPLATE_` ? das versteh ich jetzt nicht ganz

2023-05-25 13:02 UTC, col-panic commented on bundles/ch.elexis.core.mail.ui/src/ch/elexis/core/mail/ui/preference/TextTemplates.java
> +			IBlobSecondary textTemplate = CoreModelServiceHolder.get().load(id, IBlobSecondary.class).orElse(null);
same, ist das nicht unter `TEXTTEMPLATE_` gespeichert?

2023-05-30 07:54 UTC, col-panic commented
@PatrickDenzler irgendwas stimmt hier nicht, ich seh das du was reingepushed hast, die änderungen sind aber im PR nicht zur Übernahme drin - bitte schau dir das  nochmal an!

2023-05-31 09:13 UTC, closed without merging

2023-05-31 09:17 UTC, PatrickDenzler commented
pr closed due to error while pushing commits (force-push)