[25354] MailTransporter - agenda reminder
elexis/elexis-3-core pull request #524
Opened 2023-06-27 11:38 UTC by PatrickDenzler

pr für agenda reminder PreferencePage ist in gitlab

2023-06-27 11:58 UTC, col-panic requested changes

2023-06-27 11:58 UTC, col-panic commented on bundles/ch.elexis.core.mail/src/ch/elexis/core/mail/internal/MailTransporter.java
> +		mailClient = OsgiServiceUtil.getService(IMailClient.class).get();
Solltest du dir ebenfalls über `@Reference` reingeben lassen, wie auch zB den `configService` oben

2023-06-27 11:58 UTC, col-panic commented on bundles/ch.elexis.core.mail/src/ch/elexis/core/mail/internal/MailTransporter.java
> +			int startIndex = index + search.length();
das ist eigenargtig, war das nicht `subject: blablaa` wieso suchst du nach `\n`?

2023-06-27 11:58 UTC, col-panic commented on bundles/ch.elexis.core.mail/src/ch/elexis/core/mail/internal/MailTransporter.java
> +			account = mailClient.getAccount(defaultAccount);
`configService` ist oben referenziert, warum holst du ihn über en Holder?

2023-06-27 11:58 UTC, col-panic commented on bundles/ch.elexis.core.mail.ui/src/ch/elexis/core/mail/ui/preference/Preference.java
> +			@Override
Mach das als Lambda!

2023-06-28 07:26 UTC, PatrickDenzler commented on bundles/ch.elexis.core.mail/src/ch/elexis/core/mail/internal/MailTransporter.java
> +			int startIndex = index + search.length();
Ich suche hier nach \n damit der Betreff mehrere Wörter lang sein kann.

2023-06-28 10:38 UTC, col-panic commented on bundles/ch.elexis.core.mail/src/ch/elexis/core/mail/internal/MailTransporter.java
> +			int startIndex = index + search.length();
ok, du musst dann aber evtl. eine \r\n Eingabe auf Windows berücksichtigen

2023-06-28 13:29 UTC, col-panic requested changes
Gefällt mir schon gut, eine kleine Änderung bitte noch!

2023-06-28 13:29 UTC, col-panic commented on bundles/ch.elexis.core.mail/src/ch/elexis/core/mail/internal/MailTransporter.java
> +		Optional<MailAccount> account = mailClient.getAccount(messageCodes.get("account.hint"));
mach `account.hint` zu `account.id` das mit dem Hint ist glaub ich keine so gute idee. Alleine die Angabe einer `account.id` ist ja schon als hint zu betrachten, und das verwirrt sonst blos!

2023-06-28 14:21 UTC, merged