[25474] error when selecting invalid data span in AUF
elexis/elexis-3-core pull request #531
Opened 2023-08-11 08:07 UTC by alexandradenk

2023-08-11 09:03 UTC, ngiger reviewed
Please internationalize your Strings. Eg. Use Messages.EditAUFDialog_<x> instead of "Ungültige Datumsangabge".
If the error text ist not yet present in ch.elexis.core.l10n.message_de.properties you have to add a new Message ID

2023-08-15 19:55 UTC, col-panic requested changes

2023-08-15 19:55 UTC, col-panic commented on bundles/ch.elexis.core.jpa.entities/.classpath
> +	<classpathentry kind="output" path="bin"/>
Das gehört hier nicht rein!

2023-08-15 19:55 UTC, col-panic commented on bundles/ch.elexis.core.l10n/src/ch/elexis/core/l10n/messages.properties
> +AllergyIntoleranceCategory_BIOLOGIC = biologic
So sollte das nicht sein, darum der Formatter! Hier sind jede Menge Änderungen sichtbar,
die gar nicht Teil deines Patches sein sollten! Die Frage ist jetzt, ob der Formatter auch standardisiert
auf die properties files greift! Müssen wir diskutieren!

2023-08-15 19:55 UTC, col-panic commented on bundles/ch.elexis.core.ui.importer.div.native64/.classpath
> +	<classpathentry exported="true" kind="lib" path="lib" sourcepath="lib"/>
Das gehört auch nicht zu diesem patch!

2023-08-15 19:55 UTC, col-panic commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/dialogs/EditAUFDialog.java
> +					SWTHelper.showError(Messages.EditAUFDialog_invalidDateSpan,
Okay, damit zeigst du dem User einen Fehler an! Er kann aber die Selection trotzdem treffen oder? 
Umgekehrt kann ich auch das dpVon nun nach das dpBis setzen und er würde gar nichts  melden oder?

Ideal wäre, wenn dpBis eine solche, ungültige Selection gar nicht zulassen würde.

Ich hab dir auf Nextcloud ein Share freigegeben, da liegt im Ordern SS2016/presentations/ das File 03-SWT.pdf 
Für diesen spezifischen Fall hier, ab Slide 43

2023-08-15 19:55 UTC, col-panic commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/dialogs/EditAUFDialog.java
> +		return startDate.before(endDate) || startDate.equals(endDate);
Was wenn startDate oder endDate `null` sein sollten? Kann das sein? Was würde passieren?

2023-08-21 12:34 UTC, closed without merging