[25692] allowing to set default-subject vor e-mail in template
elexis/elexis-3-core pull request #556
Opened 2023-09-28 12:07 UTC by alexandradenk

notice: mpa rights have been adjusted

2023-09-28 12:35 UTC, alexandradenk commented
notice:
- mpa-rights have been reset to master
- default-subject currently overrides any other defaults that might have been defined (e.g. patient details)

2023-10-02 14:53 UTC, huthomas commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/text/TextTemplateComposite.java
> +			template.setExtInfo(MailConstants.TEXTTEMPLATE_SUBJECT, subjectText.getText()); // TODO change
Weshalb steht hier noch TODO change?

2023-10-03 07:35 UTC, huthomas requested changes

2023-10-03 07:35 UTC, huthomas commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/text/TextTemplateComposite.java
> +import org.w3c.dom.Text;
Hier sind nun falsche imports rein gekommen.

2023-10-03 07:53 UTC, merged