[24569] replace deprecated CoreHub.actMandant
elexis/elexis-3-core pull request #597
Opened 2023-11-17 08:06 UTC by PatrickDenzler

2023-11-17 14:27 UTC, huthomas commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/coolbar/MandantSelectionContributionItem.java
> +					ch.elexis.core.data.service.ContextServiceHolder.get().setActiveMandator(m);
Bitte wenn möglich die Holder Klassen aus `ch.elexis.core.services.holder` verwenden.

2023-11-17 14:27 UTC, huthomas commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/coolbar/MandantSelectionContributionItem.java
> +import ch.elexis.core.data.service.CoreModelServiceHolder;
Bitte wenn möglich die Holder Klassen aus `ch.elexis.core.services.holder` verwenden.

2023-11-17 14:27 UTC, huthomas commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/internal/CoreOperationAdvisor.java
> +				ch.elexis.core.data.service.ContextServiceHolder.get().setActiveMandator(m);
Bitte wenn möglich die Holder Klassen aus `ch.elexis.core.services.holder` verwenden.

2023-11-20 13:35 UTC, PatrickDenzler commented
Die Änderungen dieses pr sollten keine Fehler im base verursachen

2023-11-22 13:41 UTC, huthomas requested changes

2023-11-24 09:29 UTC, merged