[25447] mediOrder add stock
elexis/elexis-3-core pull request #598
Opened 2023-11-20 07:05 UTC by PatrickDenzler

IStock verwenden?

2023-11-20 09:29 UTC, col-panic requested changes

2023-11-20 09:29 UTC, col-panic commented on bundles/ch.elexis.core.jpa.entities/src/ch/elexis/core/jpa/entities/Stock.java
> +
Bitte hier einen `char(1)` vorsehen, dann können wir ggf weitere szenarien abdecken. Default ist '0'  - '1'  ist patientenlager

2023-11-20 09:29 UTC, col-panic commented on bundles/ch.elexis.core.jpa/db/v3.11/elexisdb_update.xml
> +				WHERE CHAR_LENGTH(CODE) = 7
das kann man auch über eine anweisung abbilden denke ich

2023-11-20 09:29 UTC, col-panic commented on bundles/ch.elexis.core.ui.contacts/src/ch/elexis/core/ui/contacts/views/Patientenblatt2.java
> +						Stock stock = new Stock(PATIENT_STOCK + patient.getPatientNr(), 0); // $NON-NLS-1$
das Soll in `IStockService` implementiert werden, bitte dazu auch einen Test schreiben!

2023-11-20 09:43 UTC, col-panic commented on bundles/ch.elexis.core.jpa/db/v3.11/elexisdb_update.xml
> +				WHERE CHAR_LENGTH(CODE) = 7
`code` und `type` sollen indiziert sein

2023-11-20 09:44 UTC, col-panic commented on bundles/ch.elexis.core.data/src/ch/elexis/data/Stock.java
Bitte zuerst pack nur für core teil, ohne UI. Also Core Teil + Tests

2023-12-12 13:32 UTC, col-panic commented
@PatrickDenzler der hier ist obsolet oder? Bis auf die UI Teile, aber ich nehme an da machst du einen separaten PR?

2023-12-12 13:42 UTC, PatrickDenzler commented
Ja, für den UI Teil werde ich einen neuen PR machen

2023-12-12 13:42 UTC, closed without merging