[25447] do not display patient stock
elexis/elexis-3-core pull request #618
Opened 2023-12-22 07:16 UTC by PatrickDenzler

2023-12-22 10:57 UTC, col-panic requested changes
Bitte formulier hier nochmal ganz klar, was unsere Definitions-Regeln für patienten stock sind?! Bedeutung location, responsible feld etc.

2023-12-22 10:57 UTC, col-panic commented on bundles/ch.elexis.core.jpa.entities/src/ch/elexis/core/jpa/entities/Stock.java
> -	@JoinColumn(name = "RESPONSIBLE", insertable = false)
wieso das?

2023-12-22 10:57 UTC, col-panic commented on bundles/ch.elexis.core.model/src/ch/elexis/core/model/Stock.java
> +			if (value instanceof AbstractIdModelAdapter) {
in Java 17 kannst du das zusammenfassen mit `if(value instanceof AbstractIdModelAdapter aida)`: 
1) instanceof checkt automatisch ob != null, 
2) du kannst danach die bereits gecastete Variable `aida` verwenden

2023-12-22 10:57 UTC, col-panic commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/preferences/StockManagementPreferencePage.java
> +			query.and(ModelPackage.Literals.ISTOCK__OWNER, COMPARATOR.NOT_EQUALS, patient);
Also ich weiß nicht, denk mal du hast 10000 patienten, ich glaub, dass diese sql
query dann nicht mehr funktionieren wird, einfach wegen der schieren länge die sie erreicht.

Was war nochmal die formale regel die definiert ob es ausgeblendet wird?

2023-12-22 10:57 UTC, col-panic commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/views/controls/StockDetailComposite.java
> +			query.and(ModelPackage.Literals.ISTOCK__OWNER, COMPARATOR.NOT_EQUALS, patient);
same again, evtl. sollten wir die Methode `IStockService#getAllStockEntries(boolean includePatientStock)` einführen, und die default methode `IStockService#getAllStockEntries()` soll dann `IStockService#getAllStockEntries(false)` aufrufen.

2024-01-05 08:58 UTC, PatrickDenzler commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/preferences/StockManagementPreferencePage.java
> +			query.and(ModelPackage.Literals.ISTOCK__OWNER, COMPARATOR.NOT_EQUALS, patient);
Patientenlager werden folgenermassen definiert:

1. Code: besteht aus P + Patientennummer
2. Bezeichnung: Patientenname und vorname
3. Owner: Der owner ist ein Patient (PatientenId)

2024-01-05 15:01 UTC, col-panic commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/preferences/StockManagementPreferencePage.java
> +			query.and(ModelPackage.Literals.ISTOCK__OWNER, COMPARATOR.NOT_EQUALS, patient);
Ich hab da jetzt ein paar Änderungen vorgenommen, sollten wir am Montag diskutieren!

2024-01-08 07:29 UTC, merged