Monks cleanup
elexis/elexis-3-core pull request #621
Opened 2024-01-09 08:54 UTC by debenol1

Modified various build configurations to remove warnings from the maven/tycho build

2024-01-09 08:54 UTC, debenol1 commented
No digest algorithm warnings still exist

2024-01-09 13:43 UTC, col-panic requested changes
Bundle-Vendor when missing sollte `ch.elexis` sein. Die div. Punkte müssen wir noch diskutieren!

2024-01-09 13:43 UTC, col-panic commented on bundles/ch.elexis.core.data/META-INF/MANIFEST.MF
Das musst du so lassen, sonst werden bei den Tests die Änderungen im `ch.elexis.core.data.tests` fragment nicht berücksichtigt!

2024-01-09 13:43 UTC, col-panic commented on bundles/ch.elexis.core.eigendiagnosen/build.properties
Warum `OSGI-INF/` und die einzelnen Einträge?

2024-01-09 13:43 UTC, col-panic commented on bundles/ch.elexis.core.findings.templates/pom.xml
Wieso braucht es das? Welche Meldung wird hier mitigiert?

2024-01-09 13:43 UTC, col-panic commented on bundles/ch.elexis.core.findings.util/META-INF/MANIFEST.MF
Selbes wie bei `ch.elexis.core.data`

2024-01-09 13:43 UTC, col-panic commented on bundles/ch.elexis.core.logging.osgi/pom.xml
wozu?

2024-01-09 13:43 UTC, col-panic commented on bundles/ch.elexis.core.services/META-INF/MANIFEST.MF
same as data.tests

2024-01-09 13:43 UTC, col-panic commented on bundles/ch.elexis.core.tasks/META-INF/MANIFEST.MF
same

2024-01-09 13:43 UTC, col-panic commented on bundles/ch.elexis.core.ui.stock/META-INF/MANIFEST.MF
`ch.elexis`

2024-01-13 08:59 UTC, col-panic requested changes

2024-01-13 08:59 UTC, col-panic commented on bundles/ch.elexis.core.data/META-INF/MANIFEST.MF
> -Service-Component: OSGI-INF/*.xml
bitte wieder zurück ändern!

2024-01-13 08:59 UTC, col-panic commented on bundles/ch.elexis.core.tasks/META-INF/MANIFEST.MF
> -Service-Component: OSGI-INF/*.xml
wieder zurück ändern, im tasks.test wird ein xml contributed, dass wird so nicht mehr aufgenommen

2024-01-13 08:59 UTC, col-panic commented on bundles/ch.elexis.core.test.context/.polyglot.META-INF
> +<?xml version="1.0" encoding="UTF-8"?>
datei löschen - polyglots werden dynamisch erzeugt, eigentlich sollte das in `.gitignore` sein

2024-01-13 08:59 UTC, col-panic commented on bundles/ch.elexis.core.test/META-INF/MANIFEST.MF
> +Service-Component: OSGI-INF/ch.elexis.core.test.service.TestLocalLockService.xml
bitte zurück ändern

2024-01-13 08:59 UTC, col-panic commented on bundles/ch.elexis.core.text.docx/.settings/org.eclipse.jdt.core.prefs
?? wieso ?

2024-01-13 08:59 UTC, col-panic commented on bundles/ch.elexis.core/pom.xml
das wollen wir nicht

2024-01-15 08:50 UTC, merged