[26544] dialog on mail change of activated mediorder patient
elexis/elexis-3-core pull request #695
Opened 2024-08-13 15:09 UTC by PatrickDenzler

2024-08-19 06:38 UTC, col-panic requested changes

2024-08-19 06:38 UTC, col-panic commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/propertypage/PatientPropertyPage.java
> +		textEmail.addVerifyListener(new VerifyListener() {
Das müsstest du als Lambda implementieren können, da VerifyListener ein FunctionalInterface ist. Das reduziert den ganzen Boilerplate Code hier ...

2024-08-19 06:38 UTC, col-panic commented on bundles/ch.elexis.core.ui.contacts/src/ch/elexis/core/ui/contacts/views/KontaktBlatt.java
> +			boolean hasSticker = lSticker.stream().anyMatch(sticker -> sticker.getId().equals("activate_mediorder"));
Wir haben jetzt schon an ein paar Stellen den literal String `activate_mediorder` - wir kopieren den immer, das gefällt mir nicht. Hast du einen Vorschlag wie und wo wir den als Konstante in einer Klasse ablegen können? 
Dann kannst du das dort dokumentieren, und es ist auch leicht referenzen darauf zu finden?!

2025-02-27 08:34 UTC, PatrickDenzler commented
wird in einem neuen pr weitergeführt: https://github.com/elexis/elexis-3-core/pull/799

2025-02-27 08:34 UTC, closed without merging