[26556] new orderByLeftPadded method for sorting
elexis/elexis-3-core pull request #712
Opened 2024-09-03 09:36 UTC by marcel7ag

2024-09-03 11:24 UTC, huthomas requested changes

2024-09-03 11:24 UTC, huthomas commented on bundles/ch.elexis.core.jpa/src/ch/elexis/core/jpa/model/adapter/AbstractModelQuery.java
> +				Expression<String> function = criteriaBuilder.function("LPAD", String.class,
Hier bitte noch den Kommentar  //$NON-NLS-1$ anfügen damit klar ist das der String "LPAD" nicht internationalisiert werden soll.

2024-09-05 06:19 UTC, marcel7ag commented on bundles/ch.elexis.core.jpa/src/ch/elexis/core/jpa/model/adapter/AbstractModelQuery.java
> +				Expression<String> function = criteriaBuilder.function("LPAD", String.class,
wurde angefügt.

2024-09-05 07:04 UTC, huthomas requested changes

2024-09-05 07:04 UTC, huthomas commented on bundles/ch.elexis.core.ui.contacts/src/ch/elexis/core/ui/contacts/views/PatListeContentProvider.java
> +				if (firstOrder.equals(orderFields[0])) {
Die orderFields sind konfigurierbar. D.h. `orderFields[0]` entspricht nicht immer der `patnr`.

Hier müsste dann wohl auch anhand des db Feldnamens geprüft werden ob es sich um die `patnr` handelt. Siehe `PatientenListeView:194`

2024-09-05 13:44 UTC, marcel7ag commented on bundles/ch.elexis.core.ui.contacts/src/ch/elexis/core/ui/contacts/views/PatListeContentProvider.java
> +				if (firstOrder.equals(orderFields[0])) {
hab ich nun mit einem equals check gemacht.. ich weiss nicht ob das gut ist, den string hier hardcodiert reinzuschreiben, ich hab keinen weg finden können, irgendwie einen getCode aufzurufen..

2024-09-05 14:02 UTC, marcel7ag commented on bundles/ch.elexis.core.ui.contacts/src/ch/elexis/core/ui/contacts/views/PatListeContentProvider.java
> +				if (firstOrder.equals(orderFields[0])) {
optimiert

2024-09-05 14:04 UTC, merged