[26724] rechnungsliste mandantenfilter
elexis/elexis-3-core pull request #749
Opened 2024-11-14 13:25 UTC by marcel7ag

2024-11-28 08:40 UTC, marcel7ag commented
neue klasse im ch.elexis.core.ui.e4.dialog, welche von unterschiedlichen projekten verwendet werden soll.

- ich hab paar neue booleans hinzugefügt und den ElexisEventDispatcher rausgenommen, da der deprecated ist. verwende den contextserviceholder um den activeUser Contact zu holen.
- neuer boolean noEmpty für den String "Keine Auswahl selektiert den aktiven Mandanten"
- neuer boolean nonActive, um auch nicht aktive user mandanten in die liste zu holen
- neuer boolean saveFilter, für das Speichern in den mandantenfilter cfg für die rechnungsliste.
- base constructor und einen weiteren constructor mit weniger parameter.

2024-11-28 12:00 UTC, huthomas requested changes

2024-11-28 12:00 UTC, huthomas commented on bundles/ch.elexis.core.ui.e4/src/ch/elexis/core/ui/e4/dialog/MandantSelectorDialog.java
> +	private static final String CFG_MANDATORFILTER = "rechnungsliste/mandantenfiltered";
Wäre gut wenn das in der Rechnungsliste bleibt.

2024-11-28 12:00 UTC, huthomas commented on bundles/ch.elexis.core.ui.e4/src/ch/elexis/core/ui/e4/dialog/MandantSelectorDialog.java
> +				CFG_MANDATORFILTER, StringUtils.EMPTY);
Wäre gut wenn das von der Rechnungsliste als setSelected oder so an den Dialog übergeben wird.

2024-11-28 12:00 UTC, huthomas commented on bundles/ch.elexis.core.ui.e4/src/ch/elexis/core/ui/e4/dialog/MandantSelectorDialog.java
> +		}
Wäre gut wenn da die Rechnungsliste sich getSelection holt, und dann die entsprechende config setzt.

2024-11-29 13:39 UTC, huthomas requested changes

2024-11-29 13:39 UTC, huthomas commented on bundles/ch.elexis.core.ui.e4/src/ch/elexis/core/ui/e4/dialog/MandantSelectorDialog.java
> +		}
Ansteller hier die Selection bei Ok zu sammeln, gibt es die Möglichkeit beim `ListViewer` einen `addSelectionChangedListener` zu registrieren, und dort die selection zu setzen.

`selMandators = (List<IMandator>) (List<?>) uiList.getStructuredSelection().toList()`

2024-11-29 13:39 UTC, huthomas commented on bundles/ch.elexis.core.ui.e4/src/ch/elexis/core/ui/e4/dialog/MandantSelectorDialog.java
> +	}
Dann bitte einfach das erste Element aus `selMandators` nehmen, anstelle einer separaten Variable.

2024-11-29 13:39 UTC, huthomas commented on bundles/ch.elexis.core.ui.e4/src/ch/elexis/core/ui/e4/dialog/MandantSelectorDialog.java
> +				});
Für wäre hier die Logik klarer, wenn die Liste aller Mandanten mit den ids gefiltert wird, und dann das Resultat als Selection zu setzen.

So in etwa:
`uiList.setSelection(new StructuredSelection(getMandators().stream().filter(m -> idList.contains(m.getId())).tiList())));`

2024-12-02 12:27 UTC, merged