[26834] mediorder - create medication label for rowa
elexis/elexis-3-core pull request #768
Opened 2024-12-19 10:49 UTC by PatrickDenzler

2025-02-06 06:47 UTC, col-panic requested changes
Bitte die Anmerkungen auch für https://github.com/elexis/elexis-3-base/pull/416 umsetzen!

2025-02-06 06:47 UTC, col-panic commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/dialogs/OrderImportDialog.java
> +		if (orderElement != null && !orderElement.getOrderState().equals(OrderEntryState.DONE)) {
Dreh das um, wenn du Variable.equals(Constant) hast, dann machst du im sinne der defensiven Programmierung immer Constant.equals(Variable) - sollte kein Problem sein wenn getOrderState() wohldefiniert ist, ist aber guter Stil!

2025-02-06 06:47 UTC, col-panic commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/dialogs/OrderImportDialog.java
> +			if (!orderElement.getOrderState().equals(OrderEntryState.MARKED)
siehe oben

2025-02-06 06:47 UTC, col-panic commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/dialogs/OrderImportDialog.java
> +			orderElement.setOrderState(OrderEntryState.MARKED.getValue());
same

2025-02-06 06:47 UTC, col-panic commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/dialogs/OrderImportDialog.java
> +			if (element instanceof OrderElement) {
diesen Cast kannst du dir sparen, das kannst du auch mit 
`if (element instanceof OrderElement orderElement) {` schreiben (seit Java 17 glaub ich)

2025-02-06 06:47 UTC, col-panic commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/dialogs/OrderImportDialog.java
> +		ICommandService commandService = PlatformUI.getWorkbench().getService(ICommandService.class);
Oben in dieser Classe wird ein `@Inject` gemacht, dass ist bereits e4 Style, du machst das e3 style, wovon wir eigentlich wegwollen. Bitte hol dir den ICommandService und auch den IHandlerService über `@Inject`

2025-02-06 06:47 UTC, col-panic commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/dialogs/OrderImportDialog.java
> +						OrderElement orderElement = new OrderElement(entry, stockEntry, 0);
Bitte kurz erklären warum hier 0?

2025-02-06 06:47 UTC, col-panic commented on bundles/ch.elexis.core.ui/src/ch/elexis/core/ui/dialogs/OrderImportDialog.java
>  					IStockEntry stockEntry = StockServiceHolder.get().findStockEntryForArticleInStock(stock,
Wir sollten **generell im System wegkommen von den Holder Klassen.** Versuch bitte, ob du das auch über `@Inject` kriegen kannst. Siehe auch Kommentare unten.

2025-02-06 06:47 UTC, col-panic commented on bundles/ch.elexis.core/src/ch/elexis/core/model/OrderEntryState.java
> +	OPEN(0), ORDERED(1), PARTIAL_DELIVER(2), DONE(3), MARKED(4);
Was bedeutet MARKED? Wie bindet sich das in den Workflow Ablauf ein?

2025-03-17 08:45 UTC, PatrickDenzler commented
wird in einem anderen pr weitergeführt

2025-03-17 08:45 UTC, closed without merging